#ifndef __FRAMEWORK_INPUT_MOUSEBUTTONS_H_INCLUDED__
#define __FRAMEWORK_INPUT_MOUSEBUTTONS_H_INCLUDED__

enum MOUSE_BUTTONS
{
	MOUSE_LEFT = 0,
	MOUSE_MIDDLE = 1,
	MOUSE_RIGHT = 2,
	MOUSE_WHEEL_UP = 3,
	MOUSE_WHEEL_DOWN = 4
};

#endif

