#ifndef __FRAMEWORK_LOGCATEGORIES_H_INCLUDED__
#define __FRAMEWORK_LOGCATEGORIES_H_INCLUDED__

#define LOGCAT_DEBUG "DEBUG"
#define LOGCAT_SYSTEM "SYSTEM"
#define LOGCAT_WINDOW "WINDOW"
#define LOGCAT_GAMEAPP "GAMEAPP"
#define LOGCAT_ASSETS "ASSETS"
#define LOGCAT_FILEIO "FILEIO"
#define LOGCAT_GRAPHICS "GRAPHICS"
#define LOGCAT_OPENGL "OPENGL"

#endif
