#ifdef __S3E__
#ifndef __FRAMEWORK_MARMALADESYSTEMEVENT_H_INCLUDED__
#define __FRAMEWORK_MARMALADESYSTEMEVENT_H_INCLUDED__

#include "common.h"
#include "osevent.h"

enum MARMALADE_EVENT
{
	MARMALADE_EVENT_PAUSE,
	MARMALADE_EVENT_RESUME,
	MARMALADE_EVENT_EXIT,
	MARMALADE_EVENT_GLSUSPEND,
	MARMALADE_EVENT_GLRESUME,
	MARMALADE_EVENT_SCREENRESIZE,
	MARMALADE_EVENT_KEY,
	MARMALADE_EVENT_KEYCHAR,
	MARMALADE_EVENT_POINTER_BUTTON,
	MARMALADE_EVENT_POINTER_MOTION,
	MARMALADE_EVENT_POINTER_MULTITOUCH_BUTTON,
	MARMALADE_EVENT_POINTER_MULTITOUCH_MOTION
};

struct MarmaladeSystemEvent : OSEvent
{
	MARMALADE_EVENT event;
	void *data;
};

#endif
#endif
