#ifndef __FRAMEWORK_SCREENORIENTATION_H_INCLUDED__
#define __FRAMEWORK_SCREENORIENTATION_H_INCLUDED__

enum SCREEN_ORIENTATION_ANGLE
{
	SCREEN_ANGLE_0 = 0,
	SCREEN_ANGLE_90 = 90,
	SCREEN_ANGLE_180 = 180,
	SCREEN_ANGLE_270 = 270
};

#endif
